## Boolean Filters

In [1]:
import numpy as np

In [2]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [3]:
norm_filter = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])

In [4]:
x[norm_filter]

array([2, 4, 6, 8])

In [7]:
row_filter = np.array([
    True, False, True
])

In [8]:
x[row_filter]

array([[1, 2, 3],
       [7, 8, 9]])

In [9]:
x[x%2==0]

array([2, 4, 6, 8])

In [11]:
x%2==0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [17]:
x[(x[:1]%2==0)[0,:]]

array([[4, 5, 6]])

In [13]:
x[:1]%2==0

array([[False,  True, False]])